//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DriverlessMessages
{
    [Serializable]
    public class ConeArrayMsg : Message
    {
        public const string k_RosMessageName = "driverless_messages/ConeArray";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public ConeMsg[] cone_array;

        public ConeArrayMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.cone_array = new ConeMsg[0];
        }

        public ConeArrayMsg(BuiltinInterfaces.TimeMsg stamp, ConeMsg[] cone_array)
        {
            this.stamp = stamp;
            this.cone_array = cone_array;
        }

        public static ConeArrayMsg Deserialize(MessageDeserializer deserializer) => new ConeArrayMsg(deserializer);

        private ConeArrayMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.cone_array, ConeMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.WriteLength(this.cone_array);
            serializer.Write(this.cone_array);
        }

        public override string ToString()
        {
            return "ConeArrayMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\ncone_array: " + System.String.Join(", ", cone_array.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
