//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DriverlessMessages
{
    [Serializable]
    public class GpsDataMsg : Message
    {
        public const string k_RosMessageName = "driverless_messages/GpsData";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public double x;
        public double y;
        public float yaw;
        public float pitch;
        public float roll;
        public float quat_x;
        public float quat_y;
        public float quat_z;
        public float quat_w;
        public float acc_x;
        public float acc_y;
        public float acc_z;
        public float angular_vel_x;
        public float angular_vel_y;
        public float angular_vel_z;
        public float vel_x;
        public float vel_y;
        public float vel_z;

        public GpsDataMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.x = 0.0;
            this.y = 0.0;
            this.yaw = 0.0f;
            this.pitch = 0.0f;
            this.roll = 0.0f;
            this.quat_x = 0.0f;
            this.quat_y = 0.0f;
            this.quat_z = 0.0f;
            this.quat_w = 0.0f;
            this.acc_x = 0.0f;
            this.acc_y = 0.0f;
            this.acc_z = 0.0f;
            this.angular_vel_x = 0.0f;
            this.angular_vel_y = 0.0f;
            this.angular_vel_z = 0.0f;
            this.vel_x = 0.0f;
            this.vel_y = 0.0f;
            this.vel_z = 0.0f;
        }

        public GpsDataMsg(BuiltinInterfaces.TimeMsg stamp, double x, double y, float yaw, float pitch, float roll, float quat_x, float quat_y, float quat_z, float quat_w, float acc_x, float acc_y, float acc_z, float angular_vel_x, float angular_vel_y, float angular_vel_z, float vel_x, float vel_y, float vel_z)
        {
            this.stamp = stamp;
            this.x = x;
            this.y = y;
            this.yaw = yaw;
            this.pitch = pitch;
            this.roll = roll;
            this.quat_x = quat_x;
            this.quat_y = quat_y;
            this.quat_z = quat_z;
            this.quat_w = quat_w;
            this.acc_x = acc_x;
            this.acc_y = acc_y;
            this.acc_z = acc_z;
            this.angular_vel_x = angular_vel_x;
            this.angular_vel_y = angular_vel_y;
            this.angular_vel_z = angular_vel_z;
            this.vel_x = vel_x;
            this.vel_y = vel_y;
            this.vel_z = vel_z;
        }

        public static GpsDataMsg Deserialize(MessageDeserializer deserializer) => new GpsDataMsg(deserializer);

        private GpsDataMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.quat_x);
            deserializer.Read(out this.quat_y);
            deserializer.Read(out this.quat_z);
            deserializer.Read(out this.quat_w);
            deserializer.Read(out this.acc_x);
            deserializer.Read(out this.acc_y);
            deserializer.Read(out this.acc_z);
            deserializer.Read(out this.angular_vel_x);
            deserializer.Read(out this.angular_vel_y);
            deserializer.Read(out this.angular_vel_z);
            deserializer.Read(out this.vel_x);
            deserializer.Read(out this.vel_y);
            deserializer.Read(out this.vel_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.yaw);
            serializer.Write(this.pitch);
            serializer.Write(this.roll);
            serializer.Write(this.quat_x);
            serializer.Write(this.quat_y);
            serializer.Write(this.quat_z);
            serializer.Write(this.quat_w);
            serializer.Write(this.acc_x);
            serializer.Write(this.acc_y);
            serializer.Write(this.acc_z);
            serializer.Write(this.angular_vel_x);
            serializer.Write(this.angular_vel_y);
            serializer.Write(this.angular_vel_z);
            serializer.Write(this.vel_x);
            serializer.Write(this.vel_y);
            serializer.Write(this.vel_z);
        }

        public override string ToString()
        {
            return "GpsDataMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nroll: " + roll.ToString() +
            "\nquat_x: " + quat_x.ToString() +
            "\nquat_y: " + quat_y.ToString() +
            "\nquat_z: " + quat_z.ToString() +
            "\nquat_w: " + quat_w.ToString() +
            "\nacc_x: " + acc_x.ToString() +
            "\nacc_y: " + acc_y.ToString() +
            "\nacc_z: " + acc_z.ToString() +
            "\nangular_vel_x: " + angular_vel_x.ToString() +
            "\nangular_vel_y: " + angular_vel_y.ToString() +
            "\nangular_vel_z: " + angular_vel_z.ToString() +
            "\nvel_x: " + vel_x.ToString() +
            "\nvel_y: " + vel_y.ToString() +
            "\nvel_z: " + vel_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
