# X position of a single point on the path
float32 x
# Y position of a single point on the path
float32 y
# Length of the normal vector to the left side on the driving direction in this point 
float32 width_left
# Length of the normal vector to the right side on the driving direction in this point 
float32 width_right
# Driveable velocity in this point, only needs to be filled by raceline optimization
float32 velocity -1
